### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by solvessa** [polimex/polimex-rfid#4]
stuck on connecting module
can be explained in more detail
how to add a module and use it with a controller

<function WebRfidController.post_event at 0x7f3662e7d598>, /hr/rfid/event: Function declared as capable of handling request of type 'json' but called with a request of type 'http'

Тhank

**Comment by polimex-lgeorgiev** [comment]
Thanks for notice.
We are working on new documentation. 
The functuon is defined in right way. No any error. All is working fine with equipment.

**Comment by polimex-lgeorgiev** [comment]
Upgrade modules to solve the problem (if still exists)
